### PR TITLE
fix: fix combo dropdown styles

### PR DESCRIPTION
**Pull request by carloslancha**
Before:
image

After:
image

On hold until https://github.com/liferay/liferay-ckeditor/pull/106 is merged

### CODE REVIEW

**Comment by jbalsas** [comment]
shutupandtakemymoney

**Comment by jbalsas** [comment]
There's a weird dotted line in there, though... 

just-sayin

**Comment by carloslancha** [comment]
>There's a weird dotted line in there, though...

Sh**, the focus!

**Comment by carloslancha** [comment]
@jbalsas fixed and updated screenshot. Nice catch!

**Comment by jbalsas** [comment]
Beautiful! Energize!!

**Comment by carloslancha** [comment]
image

**Pull request merged**
