### PR TITLE
fix: remove overlay that is preventing unrelated UI interactions on the page

### PR DESCRIPTION
**Pull request by markocikos**
@carloslancha @mateomustapic @wincent 

This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/145. Instead of overriding the overlay in portal, we are removing it from the source.

I am not sure what is the workflow when sending PR on this repo. I included the commit with generated build, is that correct to include? I am assuming that we need to publish to npm once this is merged. Last time I did this, but more a as a learning feat. Is it still ok for me to do it? There is also this open PR https://github.com/liferay-frontend/liferay-portal/pull/149 where we update ckeditor version, so we need to be a bit careful of conflicts.

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @markocikos could you please add some screenshots of before/after? Did you check ckeditor and allloy are working/looking as expected in the rest of portal? I'm a little worried about removing the entire class 😅

**Comment by carloslancha** [comment]
> I included the commit with generated build, is that correct to include

I usually don't include it and just build it while preparing the release, but there should be no problem.

> There is also this open PR liferay-frontend/liferay-portal#149 where we update ckeditor version, so we need to be a bit careful of conflicts.

There will be no conflicts, in that pr we're just updating version to `.4`. When we release `.5` including this we'll send another pr to portal :)

**Comment by mateomustapic** [comment]
> > I included the commit with generated build, is that correct to include
> 
> I usually don't include it and just build it while preparing the release, but there should be no problem.
> 
> > There is also this open PR [liferay-frontend/liferay-portal#149](https://github.com/liferay-frontend/liferay-portal/pull/149) where we update ckeditor version, so we need to be a bit careful of conflicts.
> 
> There will be no conflicts, in that pr we're just updating version to `.4`. When we release `.5` including this we'll send another pr to portal :)

These changes will not fix the wrong background in page editor I removed in https://github.com/liferay-frontend/liferay-portal/pull/148/commits/c76247235ceac02abf70f7c32fc988a36a655dc3. 

Also, if you @carloslancha agree, I can make a release of `.5` version after this is done and merged.

**Comment by carloslancha** [comment]
Hey @mateomustapic I'd first try to solve https://github.com/liferay-frontend/liferay-portal/pull/148 in `liferay-ckeditor` so we can ship a new version with both issues fixed. If there's no fix we can make here for that issue then it's ok for me to release `.5` once this is merged.

Anyway, we'll need to do the process together so we can find out what went wrong the last time (permissions to publish, some error during build...) and solve it for further releases 😄

**Comment by markocikos** [comment]
> These changes will not fix the wrong background in page editor I removed in [liferay-frontend/liferay-portal@c762472](https://github.com/liferay-frontend/liferay-portal/commit/c76247235ceac02abf70f7c32fc988a36a655dc3).

@mateomustapic  I am fairly certain they will, but I cannot reproduce steps in https://issues.liferay.com/browse/LPS-117468

How do you get to the point where you can edit text in hello world app? For me, nothing happens when I click on it.

**Comment by carloslancha** [comment]
@markocikos double click

**Comment by mateomustapic** [comment]
> > These changes will not fix the wrong background in page editor I removed in [liferay-frontend/liferay-portal@c762472](https://github.com/liferay-frontend/liferay-portal/commit/c76247235ceac02abf70f7c32fc988a36a655dc3).
> 
> @mateomustapic I am fairly certain they will, but I cannot reproduce steps in https://issues.liferay.com/browse/LPS-117468
> 
> How do you get to the point where you can edit text in hello world app? For me, nothing happens when I click on it.

On the Home page select `Edit` at the top and then double-click on "Hello world" text > `Edit` again

**Comment by markocikos** [comment]
This is master, today's ant all, no errors in console. I do have profile-dxp, that may cause this. There is no `Hello World` text. Do I need to turn on headers or subtitles or something similar? 

hello

**Comment by carloslancha** [comment]
Today's master  with `profile-dxp` for me. Weird...
image

**Comment by mateomustapic** [comment]
image

**Comment by markocikos** [comment]
Well, whatever the reason my hello world app is going crazy, it is unrelated to this PR. @mateomustapic you can check that either this PR or https://github.com/liferay-frontend/liferay-portal/pull/145 fixes the issue in your ticket.

**Comment by carloslancha** [comment]
> Hey @markocikos could you please add some screenshots of before/after? Did you check ckeditor and allloy are working/looking as expected in the rest of portal? I'm a little worried about removing the entire class 😅

please 🙏

**Comment by markocikos** [comment]
an example of `ckeditor` in messge boards and `alloyeditor `in web content:

Before overlay fix:

before-overlay-fix

After overlay fix:

after-overlay-fix

**Comment by carloslancha** [comment]
LGTM then

**Comment by mateomustapic** [comment]
> Hey @mateomustapic I'd first try to solve [liferay-frontend/liferay-portal#148](https://github.com/liferay-frontend/liferay-portal/pull/148) in `liferay-ckeditor` so we can ship a new version with both issues fixed. If there's no fix we can make here for that issue then it's ok for me to release `.5` once this is merged.
> 
> Anyway, we'll need to do the process together so we can find out what went wrong the last time (permissions to publish, some error during build...) and solve it for further releases 😄

I found a way to solve this in `liferay-ckeditor` and I will prepare a PR soon.

**Comment by carloslancha** [comment]
@mateomustapic nice! We'll wait for both prs to be merge to ship a new release then 🎉

**Comment by markocikos** [comment]
> Did you check ckeditor and allloy are working/looking as expected in the rest of portal? I'm a little worried about removing the entire class

I did not check all instances, that would take days if not weeks :slightly_smiling_face:   But this is a reasonably safe change, I cannot think of a specific case when such an overlay would be useful. It would make sense if the whole implementation is built around it, but that would be noticed in every single editor.

**Comment by carloslancha** [comment]
>  did not check all instances, that would take days if not weeks 🙂 But this is a reasonably safe change, I cannot think of a specific case when such an overlay would be useful. It would make sense if the whole implementation is built around it, but that would be noticed in every single editor.

Yep! I was not expecting you to check all instances, just be reasonably sure that this will not break other stuff 😄

**Comment by carloslancha** [comment]
Let's see what happens with https://github.com/liferay/liferay-ckeditor/pull/99 and decide if we ship a new version today or we wait for it

**Pull request merged**
