### PR TITLE
fix: CodeMirror plugin cannot handle multiple instances

### LINKED ISSUE #184: CodeMirror plugin cannot handle multiple instances
**Issue description**: When using multiple ckeditor instances with source mode, codemirror's instance will always point towards the last editor that entered source mode.

Reproduction steps with [LPS-136195](https://issues.liferay.com/browse/LPS-136195)

- Setup Liferay DXP and make sure to set the following properties (not needed for master):
`editor.wysiwyg.portal-impl.portlet.ddm.text_html.ftl=ckeditor editor.wysiwyg.portal-web.docroot.html.portlet.announcements.edit_entry.jsp=ckeditor editor.wysiwyg.portal-web.docroot.html.portlet.blogs.edit_entry.jsp=ckeditor`
- Create a web content structure TestStructure with 2 HTML fields
- Create a web content template with this structure connected to the template
- Create a web content useing TestStructure
- Put the value for the first HTML field to "field 1"
- Put the value for the second HTML field to "field 2"
- Enable Source mode for the first HTML field
- Copy the content from the first HTML field
- Enable Source mode for the second HTML field
- Paste the copied content from the first HTML field to the second HTML field
- Switch Source mode back normal for the second HTML field
- Update the value for the first HTML field to "new content for field 1"
- Switch Source mode back normal for the first HTML field

Solution proposal: create another instance and use that for codeMirrorEditor and its handlers

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-136195](https://issues.liferay.com/browse/LPS-136195)

I created codeMirrorInstance for codeMirrorEditor to make sure it can handle multiple instances of the ckeditor with the source plugin. Please review my changes

Fixes #184

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]
Looks good to me! It works well in master :)

**Comment by diegonvs** [comment]
Hey @NemethNorbert, could you add a "Fixes #184" in the PR description? It will help to close the issue automatically once merged :)

**Comment by NemethNorbert** [comment]
Hey @diegonvs ,

I hope I managed to accomplish the PR description update as you wanted :) Could you please move this PR forward if you don't see any issue with it? 
Thank you

**Review by markocikos — APPROVED** [review]
LGTM!

**Pull request merged**
