### PR TITLE
feat: customize moono-lexicon skin

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/IFI-1773

Applying in the moono-lexicon skin the new Lexicon styles already implemented in portal so we can get rid of that styles there.

Once we merge this and release a new liferay-ckeditor version we will need to:
- Remove `_editor_ckeditor.scss`
- Remove `.html-editor.portlet` definition on the `editor_html.scss` theme file.
- Update `BaseCKEditorConfigContributor` to load `moono-lexicon` css instead of `frontend-css-web` one. 

Also I opened [an issue](https://github.com/liferay/liferay-ckeditor/issues/68) to discuss if we should support scss for skins. For this pr I harcoded colors instead using clay variables.

Steps to test this in portal:
- Run `ck.sh build` in `liferay-ckeditor`
- Remove `liferay-ckeditor` folder from `/modules/node_modules` in portal
- Create a symlink to your `liferay-ckeditor` local path in `modules/node_modules` in portal (or just copy the entire project)
- Remove the file `modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/portal/_editor_ckeditor.scss` and deploy the module.
- Remove the `.html-editor.portlet` definition from `modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/application/_editor_html.scss` and deploy the module.
- Go to file `modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/java/com/liferay/frontend/editor/ckeditor/web/internal/editor/configuration/BaseCKEditorConfigContributor.java` and replace the content with [this one](https://gist.github.com/carloslancha/66774ad1e08605cbe879a956244d7f98)
- Remove `build`, `classes` and `tmp` folders and deploy the module (avoid clean deploy)
- Go to Product Menu / Content & Data / Web Content / New Basic Web Content

Note: I added here styles for the focus state, you need to focus the editor content and then press Alt + F10 (Win) or Option + F10 (Mac) to focus the toolbar in order to test it.

image

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @wincent @jbalsas @marcoscv-work

**Comment by jbalsas** [comment]
Screenshot looks good!

I'm guessing this is just a 1:1 of the skin modifications we have on `liferay-portal`, correct? And that we're planning to work on the icons once we have this in?

I'm good with this going in and integrating it in DXP 👍

**Comment by carloslancha** [comment]
@jbalsas it's 1:1 plus a couple of things that were missing. And I'll work on the icons after this, yep :)

**Comment by wincent** [comment]
> I'm good with this going in

Same. A couple of minor nits that you can decide whether you care about @carloslancha:

Screenshot 2020-06-19 -120926-Py5km4yV@2x

I don't think we should use tabs to align trailing comments. As the screenshot shows, their "alignedness" is dependent on display characteristics. I'd just put them right after the property, separated by one space. There are already comments in the files that follow that convention.

Also, I see we've switch from lowercase to uppercase color values, but only on the lines that we've touched, so we have an inconsistent mix.

**Comment by jbalsas** [comment]
> Also, I see we've switch from lowercase to uppercase color values, but only on the lines that we've touched, so we have an inconsistent mix.

`yarn format` FTW? :D

**Comment by carloslancha** [comment]
@wincent @jbalsas added skins folder to `yarn format` script and formated. Merging this!

**Comment by naderjafari** [comment]
Hi @carloslancha
I've faced this bug in latest version of liferay CE - 7.3 GA6.
I can't select texts in Ck Editor by mouse!
I found this lines in this file that cause this issue :
modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/portal/_editor_ckeditor.scss
```

&:after {
		border: 1px solid $secondary-l3;
		bottom: 0;
		content: '';
		left: 0;
		position: fixed;
		right: 0;
		top: 0;
	}
```
I disabled this styles and And everything went well.
What does this lines do exactly?



Related to : https://issues.liferay.com/browse/LPS-112480

**Pull request merged**
