### PR TITLE
revert: "Merge pull request #102 from julien/LPS-116683"

### PR DESCRIPTION
**Pull request by carloslancha**
This code is causing this error on `build`

```
Copying files (relax, this may take a while)
Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: plugin.js:121: WARNING - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
                        },
                         ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:34: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        afterInit(editor) {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:44: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        getToolbarsWidth() {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:58: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        isToolbarOverflowing() {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:78: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        onInstanceReady(event) {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:114: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        onLoad() {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 5 error(s), 1 warning(s)
Exception in thread "main" org.mozilla.javascript.JavaScriptException: Unable to compile file: /Users/greghurrell/code/liferay-ckeditor/ckeditor-dev/dev/builder/release/ckeditor/plugins/toolbarwatcher/plugin.js (C:\ckbuilder\src/lib/javascript.js#68)
        at ckbuilder.lib.javascript._c_compileFile_2(C:\ckbuilder\src/lib/javascript.js:68)
        at ckbuilder.lib.javascript.call(C:\ckbuilder\src/lib/javascript.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at ckbuilder.lib.javascript._c_anonymous_5(C:\ckbuilder\src/lib/javascript.js:167)
        at ckbuilder.lib.javascript.call(C:\ckbuilder\src/lib/javascript.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at ckbuilder.lib.builder._c_anonymous_14(C:\ckbuilder\src/lib/builder.js:454)
        at ckbuilder.lib.builder.call(C:\ckbuilder\src/lib/builder.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at ckbuilder.lib.io._c_anonymous_9(C:\ckbuilder\src/lib/io.js:285)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.io._c_anonymous_9(C:\ckbuilder\src/lib/io.js:299)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.io._c_anonymous_9(C:\ckbuilder\src/lib/io.js:299)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.io._c_anonymous_9(C:\ckbuilder\src/lib/io.js:299)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.builder._c_copyFiles_12(C:\ckbuilder\src/lib/builder.js:376)
        at ckbuilder.lib.builder.call(C:\ckbuilder\src/lib/builder.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at ckbuilder.lib.builder._c_anonymous_20(C:\ckbuilder\src/lib/builder.js:691)
        at ckbuilder.lib.builder.call(C:\ckbuilder\src/lib/builder.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
        at ckbuilder.lib.controller._c_anonymous_5(C:\ckbuilder\src/lib/controller.js:78)
        at ckbuilder.lib.controller.call(C:\ckbuilder\src/lib/controller.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.controller._c_anonymous_14(C:\ckbuilder\src/lib/controller.js:235)
        at ckbuilder.lib.controller.call(C:\ckbuilder\src/lib/controller.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at ckbuilder.ckbuilder._c_script_0(C:\ckbuilder\src/ckbuilder.js:112)
        at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
        at ckbuilder.ckbuilder.exec(C:\ckbuilder\src/ckbuilder.js)
        at org.mozilla.javascript.optimizer.OptRuntime$1.run(OptRuntime.java:218)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.optimizer.OptRuntime.main(OptRuntime.java:206)
        at ckbuilder.ckbuilder.main(C:\ckbuilder\src/ckbuilder.js)
^C\n\nAborting.\n
```

I was able to fix it by removing ES6 syntax but couldn't see the plugin working in portal (styles are not being loaded correctly), so I decided to leave this out of the release and investigate the issue after it.

### CODE REVIEW

**Comment by carloslancha** [comment]
Finally manually removed the commits of this revert and the original pr so doesn't appear in the release CHANGELOG.

**Comment by wincent** [comment]
> Finally manually removed the commits of this revert and the original pr so doesn't appear in the release CHANGELOG.

The way the changelog generator works it will show _all_ merge commits (unless you manually edit the merge commit message to depart from the standard GitHub format). ie. I would expect it to show one entry for the original change and another for the revert. It's totally fine though to edit the changelog by hand though after running the generator.

**Comment by carloslancha** [comment]
If you edit the CHANGELOG manually after generating, won't those edited things be regenerated next time you run the generator?

**Comment by wincent** [comment]
@carloslancha: no, because if you edit version X and publish, when you come to release version X + 1, it is only going to _add_ the changes from version X + 1, it doesn't go back and regenerate the whole thing. This is by design, to allow exactly this kind of editing workflow.

Example:

- Run generator, fix mistakes, `git add` result, release v1.0.

**Comment by carloslancha** [comment]
Roger that, I thought everything was regenerated based on (probably bad) memories from other projects. Thx!

**Comment by julien** [comment]
@carloslancha this should be fixed by #114.
concerning styles in portal, I checked multiple times and saw it working so I'm wondering what's happening

**Pull request merged**
