### PR TITLE
fix: improve accessibility of caption styles

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by wincent** [comment]
Assigned this one to @julien seeing as you two already discussed this over on [LPS-123682](https://issues.liferay.com/browse/LPS-123682).

@robertoDiaz, I retitled the PR for you to start with `fix:` because the Semantic Pull Request bot will complain about anything that doesn't follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format. Would you mind `git commit --amend`-ing the commit and force-pushing to update the PR to make the bot happy (it'll only turn green when _both_ PR and commit titles follow the format).

**Comment by julien** [comment]
thanks @wincent.

@marcoscv-work, @eduardoallegrini  could you tell me what you think about these changes, and which way we should fix it when you have time? thanks

**Comment by marcoscv-work** [comment]
This PR would "fix the issue" only in the edit view, so we think we need to fix it in all places/situations, that's the reason we have created new issues in Clay and a request for the Lexicon team:
- https://github.com/liferay/clay/issues/3806
- https://issues.liferay.com/browse/LEXI-1076

We need to discuss with Lexicon what is the correct place for table captions (top or bottom) and maybe think about the possibility to change the edit textarea bg color.

So guys, can we close this PR and try to fix the root problem (no definition in Lexicon/Clay)?

**Comment by julien** [comment]
@marcoscv-work i don't mind closing it, but I just want to make sure we don't forget about @robertoDiaz :)

**Comment by marcoscv-work** [comment]
> @marcoscv-work i don't mind closing it, but I just want to make sure we don't forget about @robertoDiaz :)

Yeah! of course!
It would be perfect if we could prioritize this since it is coming from a support bug.
And actually, the bg-gray in the editor is a potential hive of contrast accessibility bugs.
Since what you are editing in ckeditor is conceptualized to be finally rendered in a white bg (if we want to ensure accessibility).

**Comment by julien** [comment]
assigned to @marcoscv-work since he'll be working on this with @victorvalle

**Comment by robertoDiaz** [comment]
Hey @marcoscv-work 

@wincent suggested me to change the commit message, but if I understand it well this code is going to be discarded.

Do I have to change the commit message?

**Comment by wincent** [comment]
@robertoDiaz: Don't bother changing the commit message just yet. Let's wait until we hear confirmation from @marcoscv-work that he's actually going to take over — his last comment ("It would be perfect if we could prioritize this") makes it sound like he is waiting for a green light (if so, from where?). Once we have clarity on that we can decide whether to close this or proceed with it (at which point, yes, we would have to amend the commit message in order to get a green CI run).

**Comment by robertoDiaz** [comment]
Hey @marcoscv-work 

What is the current status of this?

Thanks!!

**Comment by pat270** [comment]
This should be fixed by https://github.com/liferay/clay/pull/3822. Can we close this pr?

**Comment by wincent** [comment]
> This should be fixed by [liferay/clay#3822](https://github.com/liferay/clay/pull/3822). Can we close this pr?

Thanks @pat270. I'm going to update the LPS with a link to your alternative fix.

**Pull request closed without merging**
