### PR TITLE
fix: add skin files for plugins that support skinning

### PR DESCRIPTION
**Pull request by julien**
In [85bfdebb7f23872a9d6dfb94d4de49325d6df618](https://github.com/liferay/liferay-ckeditor/pull/67/commits/85bfdebb7f23872a9d6dfb94d4de49325d6df618),
we created a new (`moono-lexicon`) skin for CKEditor,
but some plugins also support skinning and can't be used correctly
with our custon `moono-lexicon` skin.

These are the plugins that also need css files in a `moono-lexicon`
directory in order to work correctly

| Plugin name  | Skin directory |
| ------------ | -------------- |
| a11ychecker  | ./ckeditor-dev/plugins/a11ychecker/skins |
| balloonpanel | ./ckeditor-dev/plugins/balloonpanel/skins |
| balloontoolbar | ./ckeditor-dev/plugins/balloontoolbar/skins |
| scayt | ./ckeditor-dev/plugins/scayt/skins |
| wsc | ./ckeditor-dev/plugins/wsc/skins |

At the moment, we're using the files that come with the default
`moono-lisa` skin, and if we need to we can customize these to our liking

Test plan:
- With the current version of `liferay-ckeditor` in `liferay-portal`,
  try to use the `balloonpanel` plugin and see it fail because of missing css files

  The error looks like this
  ```
  Refused to apply style from
  'http://localhost:8080/o/frontend-editor-ckeditor-web/ckeditor/plugins/balloonpanel/skins/moono-lexicon/balloonpanel.css'
  because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
  ```

- Run `./ck.sh build`
- Try to use the `balloonpanel` plugin and see it working correctly

Closes https://issues.liferay.com/browse/IFI-1858

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @julien could you please add more detail on how to use balloonpanel plugin?

**Comment by wincent** [comment]
> Whatever the case, this doesn't make things _worse_, so I'm going to merge it.

Unless you have any objections, that is, @carloslancha. (Aren't you on PTO?)

**Comment by carloslancha** [comment]
I am but I'm interested on this since I started yesterday looking into It. If it's working I'm fine with merging it, I have some doubts about how skins and plugins works and I wanted to do a couple of test to see if we can simplify the process, but that's something we can iterate over if needed.

Go for it so we don't block @julien and @mateomustapic , I'll take a look on Monday and let you know if I find something. Thx guys!

**Comment by wincent** [comment]
Ok.

lets-do-this

**Comment by julien** [comment]
> Hey @julien could you please add more detail on how to use balloonpanel plugin?

@carloslancha sure: the `balloonpanel` plugin is a dependency of the `a11ychecker` plugin but you can also use it directly.
All is needed is to add it to `extraPlugins` in your editor's configuration.

@wincent I'll check what you mentioned and notify if I find anything

**Pull request merged**
