### PR TITLE
feat: autocommit build artifacts after `./ck.sh build`

### PR DESCRIPTION
**Pull request by wincent**
To avoid the kind of accidental submodule changes discussed in [this PR](https://github.com/liferay-frontend/liferay-portal/pull/66).

Note that if you run multiple builds in a row, you will have multiple commits, and it is on you to squash them (ie. with `git rebase -i`).

Test plan: Run `./ck.sh build` and see this change (with `git whatchanged`):

    commit 0ddb4fde5882e8cdcfc37a2524fcc0be4577acea
    Author: Greg Hurrell <greg.hurrell@liferay.com>
    Date:   Wed Jul 1 14:49:46 2020 +0200

        chore: update ckeditor build artifacts

        This commit autogenerated with "./ck.sh".

    :100644 100644 12d30fb255 ee812c28d1 M  ckeditor/CHANGES.md
    :100644 100644 0d7625165a 22ae688c74 M  ckeditor/LICENSE.md
    :100644 100644 3aa2ffa0d9 ba745105ec M  ckeditor/adapters/jquery.js
    :100644 100644 2b3469a6ea 9b5416b18f M  ckeditor/ckeditor.js
    :100644 100644 14a9c2e592 21631c4752 M  ckeditor/config.js
    :100644 100644 de1167fe9d 20e84053a2 M  ckeditor/contents.css
    ... etc

Note that we only do this for non-`DEBUG` builds, because committing debug artifacts would be bad.

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by wincent** [comment]
As @julien pointed out, `git wc` in the test plan should be `git whatchanged`; I forgot that `wc` was a local alias that I have and not the actual name of the command. Sorry!

**Comment by julien** [comment]
Thanks @wincent , looks good to me.

Ran `./ck.sh build` and `git whatchanged` and it showed me what I expected 

image

(Yes this screenshot is truncated because there are a lot of changes)

**Comment by wincent** [comment]
@carloslancha Your gif game has been really inspiring of late.

inspiring

**Pull request merged**
