### PR TITLE
Update to v4.21.0

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://github.com/liferay/liferay-ckeditor/issues/205

Update to CKEditor 4.21.0.

Please let me know if this is the correct process.

Thank you!

### CODE REVIEW

**Comment by markocikos** [comment]
@fortunatomaldonado When you updated base version, were our 15 commits successfully rebased on top of `liferay` branch on `ckeeditor-dev`? If there were no conflicts, great! 

What's missing in this PR is the update to `patches` folder, probably you just need to do `./ck.sh patch`. Add that commit, and we can merge PR. I believe this does not affect build artifacts, that our changes were included.

You also need to [publish new version on npm](https://github.com/liferay/liferay-ckeditor#publishing-the-liferay-ckeditor-package-to-npm). There should be a new `4.21.0-liferay.1` version [here](https://www.npmjs.com/package/liferay-ckeditor?activeTab=versions).

**Comment by fortunatomaldonado** [comment]
Hello @markocikos,
I did find a conflict with patch 0013 that I was able to fix and merge. I then updated the patches.
Let me know if there is anything else needed to be fixed.

Once this is merge, I should create the new version on npm correct?

Thank you for taking a look at this!

**Comment by markocikos** [comment]
@fortunatomaldonado are you sure that changes in patches are included in the latest build artifacts?

**Comment by fortunatomaldonado** [comment]
@markocikos, I believe so but I could be wrong. 
I went into ckeditor-web, made the changes, ran `git add` and `git am --continue` and then ran build.

Please correct me if I am messing up the process.
Thank you for your help!

**Comment by fortunatomaldonado** [comment]
Hello @markocikos,
Is there some other way you would like me to try this?
Thank you!

**Comment by markocikos** [comment]
@fortunatomaldonado just doublechecking, but this looks good! After this is merged, you can do the [publish part](https://github.com/liferay/liferay-ckeditor#publishing-the-liferay-ckeditor-package-to-npm). Note that the publish script both pushes to this repo and to npm, hopefully all permissions are set for you. The version we want is `4.21.0-liferay.1`. If something goes wrong, let me know and I'll complete the release.

**Pull request merged**
