### PR TITLE
fix: adjusts richcombo styles when rendering rtl languages

### PR DESCRIPTION
**Pull request by diegonvs**
**Before:**

https://user-images.githubusercontent.com/7663513/144684814-cf3a05a4-96a2-48db-92df-d2849ea2b0e0.mov

**After:**

https://user-images.githubusercontent.com/7663513/144684851-eba590bc-ef28-48bd-b751-61afd134d36a.mov

What need to be done:

<strike>
When `./ck.sh build` and then updating build things on DXP, it is not update. Does somebody have any clue?

Screen Shot 2021-12-03 at 20 24 27

Literally what needs to be done is 

Change .cke_rtl .cke_combo_off a.cke_combo_button:hover

- Change `padding` to `6px 18px;`

- Remove `margin-left: -1px;`
- Remove `margin-right: 0;`
- Change the `margin` to: `0 0 0 4px;`

When I do this on browser level, it seems ok. However, using this build artifact it is not updated

</strike>

Fixed!

### CODE REVIEW

**Comment by diegonvs** [comment]
Push force with a new version, see the recording:

https://user-images.githubusercontent.com/7663513/144877287-a06169f0-97a9-405f-b796-ba4c785789b7.mov

**Comment by diegonvs** [comment]
Now, it's ready for review!

**Comment by bryceosterhaus** [comment]
LGTM! Nice job @diegonvs

**Review by markocikos — APPROVED** [review]
LGTM!

**Pull request merged**
