### PR TITLE
fix: remove obsolete summary field from table elements

### PR DESCRIPTION
**Pull request by rolandpakai**
Please check my patch.

https://github.com/liferay/liferay-ckeditor/issues/55
https://issues.liferay.com/browse/LPP-36989

### CODE REVIEW

**Comment by wincent** [comment]
Taking a look.

**Comment by wincent** [comment]
Rebased this for you. I think it looks good to merge. I'm just going to test it in liferay-portal before pulling the trigger on it.

**Comment by rolandpakai** [comment]
Thank you @wincent

**Comment by wincent** [comment]
Just did a couple of edits to the PR title to prove that the semantic PR bot is indeed working as requested in https://github.com/liferay/liferay-ckeditor/pull/60:

## Bad title

CleanShot 2020-04-15 at 10 46 29@2x

## Good title

CleanShot 2020-04-15 at 10 46 51@2x

So, it works!

**Comment by wincent** [comment]
Sorry it took so long, but I tested this and it seems fine...

CleanShot 2020-04-15 at 18 12 28@2x

**Comment by wincent** [comment]
@rolandpakai: PR updating this in liferay-portal is now with you here: https://github.com/rolandpakai/liferay-portal/pull/19

**Comment by rolandpakai** [comment]
Thank you again @wincent

**Pull request merged**
